version: 2

project_name: pano

builds:
  - id: pano
    main: ./cmd/pano
    binary: pano
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/michaelpeterswa/bigpictures.company/internal/version.Version={{.Version}}
      - -X github.com/michaelpeterswa/bigpictures.company/internal/version.Commit={{.ShortCommit}}
      - -X github.com/michaelpeterswa/bigpictures.company/internal/version.Date={{.Date}}

archives:
  - id: pano
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - SPEC.md

checksum:
  name_template: "checksums.txt"

release:
  draft: true

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  use: github
